# Generated by Django 6.0.7 on 2026-07-23 14:11

import utils.model_validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_setup', '0004_sitesetup_favicon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetup',
            name='favicon',
            field=models.ImageField(blank=True, default='', upload_to='assets/favico/%Y/%m', validators=[utils.model_validators.validate_png]),
        ),
    ]
